/* TAGS */
export const ROOM_GAME_TAG = "ROOM_GAME_TAG";
export const PREGAME_ZONE_TAG = "PREGAME_ZONE_TAG";
export const PLAYER_CHARACTER_TAG = "PLAYER_CHARACTER_TAG";
export const PLAYER_UPPER_TORSO_TAG = "PLAYER_UPPER_TORSO_TAG";

/* PREGAME */
export const WAIT_PLAYERS_PREGAME = 15;
